server:
  port: 8080

spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.78.201.166:3306/backend
    username: admin
    password: ${Mysql.password}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:/home/ec2-user/image/
upload:
  directory: /home/ec2-user/image
